name: flutter_dice_app
description: "A new Flutter project."
publish_to: 'none'

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

# Dependencies for the app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.27 # For playing sound effects

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/audios/
